from typing import Dict


def report_json_to_txt(report: Dict) -> str:
    meta = report.get("metadata", {})
    product = report.get("product_data", {})
    llm = report.get("llm_analysis", {})
    sentiment = llm.get("sentiment", {})
    themes = llm.get("themes", {})

    lines = []
    lines.append(f"ASIN: {meta.get('asin','N/A')}")
    lines.append(f"Titolo: {product.get('title','N/A')}")
    lines.append(f"Rating medio: {product.get('rating_average',0)} | Totale recensioni: {product.get('total_reviews',0)}")
    lines.append("")
    lines.append("Sentiment")
    lines.append(f"  Generale: {sentiment.get('sentiment_generale','N/A')} (conf: {sentiment.get('confidence',0)})")
    dist = sentiment.get('distribuzione') or sentiment.get('distribution') or {}
    if dist:
        lines.append(f"  Distribuzione: +{dist.get('positivo',0)} / 0 {dist.get('neutro',0)} / -{dist.get('negativo',0)}")
    lines.append("")
    if themes:
        strengths = ', '.join(themes.get('strengths', themes.get('punti_forza', []))[:5])
        weaknesses = ', '.join(themes.get('weaknesses', themes.get('punti_deboli', []))[:5])
        lines.append("Temi principali")
        if strengths:
            lines.append(f"  Punti forza: {strengths}")
        if weaknesses:
            lines.append(f"  Punti deboli: {weaknesses}")
    lines.append("")
    lines.append("Generated by Amazon Review Agent")
    return "\n".join(lines)

